version: '3.8'

services:
  react:
    build:
      context: ./react-project
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./react-project:/app
    environment:
      # Docker for Mac/Windows などの場合、ホットリロードのために必要な場合あり
      - CHOKIDAR_USEPOLLING=true

  flask:
    build:
      context: ./flask-app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./flask-app:/app
    environment:
      - FLASK_APP=app.py
